### ISSUE TITLE
Failed to export Metrics to StackDriver

### ISSUE THREAD

**Issue by sherifkozman** [google/exposure-notifications-server#704] opened 2020-07-08 16:44 UTC
The latest update for Cloud run permissions resulting the below errors : 

Failed to export to Stackdriver: rpc error: code = InvalidArgument desc = One or more TimeSeries could not be written: Points must be written in order. One or more of the points specified had an older start time than the most recent point.: timeSeries

**Comment by sethvargo** [comment] 2020-07-08 16:59
Hi @sherifkozman these are not permission errors, something is wrong with some of our metrics. Dupe of GH-699.

**Closed by sethvargo** 2020-07-08 16:59 UTC
Labels: kind/bug
